### ISSUE TITLE
Error in emd2

### ISSUE THREAD

**Issue by toreerdmann** [zsteve/OptimalTransport.jl#40] opened 2021-04-21 08:47 UTC
Hello,
I wanted to report that the following produces an error for me:
```
thetas = range(0, step = pi/6, length = 12)
costmat = [1 - cos(th1 - th2) for th1 in thetas, th2 in thetas]
p = [0.0, 0.0, 0.0, 0.0, 0.0, 0.3249465782947873, 0.0, 0.0, 0.3501068434104255, 0.0, 0.0, 0.3249465782947873]
q = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
OptimalTransport.emd2(p, q, costmat, Tulip.Optimizer())
```
However, it works when using OptimalTransport.POT.emd2 or if I slightly tweak the q vector (reducing 1.0 to .99).
The error message reads: "ERROR: BoundsError: attempt to access 1-element Array{Float64,1} at index [21]"

I am gonna use OptimalTransport.POT.emd2, but I thought its better to report it.

**Comment by devmotion** [comment] 2021-04-21 09:23
I can reproduce this error with a clean environment (Julia 1.6, OptimalTransport + Tulip):
```julia
julia> OptimalTransport.emd2(p, q, costmat, Tulip.Optimizer())
ERROR: BoundsError: attempt to access 1-element Vector{Float64} at index [21]
Stacktrace:
  [1] setindex!
    @ ./array.jl:839 [inlined]
  [2] remove_empty_row!(ps::Tulip.PresolveData{Float64}, i::Int64)
    @ Tulip ~/.julia/packages/Tulip/SEzZJ/src/Presolve/empty_row.jl:38
  [3] remove_fixed_variable!(ps::Tulip.PresolveData{Float64}, j::Int64)
    @ Tulip ~/.julia/packages/Tulip/SEzZJ/src/Presolve/fixed_variable.jl:48
  [4] remove_row_singleton!(ps::Tulip.PresolveData{Float64}, i::Int64)
    @ Tulip ~/.julia/packages/Tulip/SEzZJ/src/Presolve/row_singleton.jl:69
  [5] remove_row_singletons!(ps::Tulip.PresolveData{Float64})
    @ Tulip ~/.julia/packages/Tulip/SEzZJ/src/Presolve/Presolve.jl:611
  [6] presolve!(ps::Tulip.PresolveData{Float64})
    @ Tulip ~/.julia/packages/Tulip/SEzZJ/src/Presolve/Presolve.jl:411
  [7] macro expansion
    @ ./timing.jl:287 [inlined]
  [8] optimize!(model::Tulip.Model{Float64})
    @ Tulip ~/.julia/packages/Tulip/SEzZJ/src/model.jl:90
  [9] optimize!
    @ ~/.julia/packages/Tulip/SEzZJ/src/Interfaces/MOI/MOI_wrapper.jl:169 [inlined]
 [10] solveLP(c::Vector{Float64}, A::LazyArrays.ApplyArray{Float64, 2, typeof(vcat), Tuple{LazyArrays.ApplyArray{Float64, 2, typeof(kron), Tuple{FillArrays.Ones{Float64, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}, LinearAlgebra.Diagonal{Float64, FillArrays.Ones{Float64, 1, Tuple{Base.OneTo{Int64}}}}}}, LazyArrays.ApplyArray{Float64, 2, typeof(kron), Tuple{LinearAlgebra.Diagonal{Float64, FillArrays.Ones{Float64, 1, Tuple{Base.OneTo{Int64}}}}, FillArrays.Ones{Float64, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}}}}}, b::LazyArrays.ApplyArray{Float64, 1, typeof(vcat), Tuple{Vector{Float64}, Vector{Float64}}}, model::Tulip.Optimizer{Float64})
    @ OptimalTransport ~/.julia/packages/OptimalTransport/iH0KJ/src/simplex.jl:78
 [11] emd(μ::Vector{Float64}, ν::Vector{Float64}, C::Matrix{Float64}, optimizer::Tulip.Optimizer{Float64})
    @ OptimalTransport ~/.julia/packages/OptimalTransport/iH0KJ/src/OptimalTransport.jl:54
 [12] emd2(μ::Vector{Float64}, ν::Vector{Float64}, C::Matrix{Float64}, optimizer::Tulip.Optimizer{Float64})
    @ OptimalTransport ~/.julia/packages/OptimalTransport/iH0KJ/src/OptimalTransport.jl:76
 [13] top-level scope
    @ REPL[9]:1
```

To me it seems this error is caused by Tulip (or should at least handled differently there and not result in a BoundsError).

**Comment by devmotion** [comment] 2021-04-21 09:52
The error is fixed by https://github.com/ds4dm/Tulip.jl/pull/96.

**Comment by devmotion** [comment] 2021-04-21 09:54
Thank you for the example and for opening an issue!

**Comment by devmotion** [comment] 2021-04-21 11:30
The issue should be fixed if you update Tulip.

**Closed by devmotion** 2021-04-21 11:30 UTC
